# DEVELOPMENT

version: "3.7"

services:
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    volumes:
      - ./node:/node
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - ./node/.env
